###
# Get all books - Books module
GET {{RiverBooks_WebHostAddress}}/books/
Accept: application/json

###
# Get a book - Books module
GET {{RiverBooks_WebHostAddress}}/books/12c87934-3fac-4008-8553-49aecc4bd762

###
# Add a new book - Books module
POST {{RiverBooks_WebHostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "title": "New book test",
  "author": "Alexei P",
  "price": 10.990000
}

###
# Delete a book - Books module
DELETE {{RiverBooks_WebHostAddress}}/books/12c87934-3fac-4008-8553-49aecc4bd762

###
# Update price of a book - Books module
POST {{RiverBooks_WebHostAddress}}/books/98999DE8-FBEF-4918-ADFE-DDA0F8B702D9/pricehistory
Accept: application/json
Content-Type: application/json

{
"newPrice": -1
}

###
# Create new user - Users module
POST {{RiverBooks_WebHostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "alexei6@test.com",
  "password": "Password1!"
}

###
# Login - Users module
POST {{RiverBooks_WebHostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "alexei@test.com",
  "password": "Password1!"
}

###
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJhbGV4ZWlAdGVzdC5jb20iLCJpYXQiOjE3MjU3NDE0NjEsImV4cCI6MTcyNTc0NTA2MSwibmJmIjoxNzI1NzQxNDYxfQ.yqCIuCNbW2dI1OrYpOueXoj2SEq-icy6oRWH2yJZHRM

# Add item to cart - Users module
POST {{RiverBooks_WebHostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId": "eb9dcad0-6986-43ff-9a25-11fc79a31448",
  "quantity": 1
}

###
# List items in cart - Users module
GET {{RiverBooks_WebHostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###
# Get orders - Order Processing module
GET {{RiverBooks_WebHostAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###
# Checkout cart - Users module
POST {{RiverBooks_WebHostAddress}}/cart/checkout
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "shippingAddressId": "f458227b-b438-4031-b181-f84a4c63db9f",
  "billingAddressId": "f458227b-b438-4031-b181-f84a4c63db9f"
}

###
# Add address to user = Users module
POST {{RiverBooks_WebHostAddress}}/users/addresses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "street1": "4 Main St",
  "street2": "Number 78",
  "city": "Antown",
  "state": "NY",
  "postalCode": "11111",
  "country": "US"
}

###
# Flush Redis cache
POST {{RiverBooks_WebHostAddress}}/flushcache